In [5]:
import numpy as np
from scipy import linalg
import sympy as sp

A = np.array([[5,3,-5,5], 
              [3,5,1,3], 
              [-5,1,10,-5],
              [-1,-1,1,1]])
y = np.array([1,1,1,0])

x = np.linalg.inv(A).dot(y)
print(x)


[-5.40431955e+15  3.37769972e+15 -2.70215978e+15  6.75539944e+14]


In [19]:
import numpy as np
from sklearn.svm import SVC

X = np.array([[1,2],[-1,2],[3,1],[-1,-2]] )
y = np.array([-1,-1, 1, 1])

clf = SVC(C = 1, kernel = 'linear')
clf.fit(X, y) 

SVC(C=1, kernel='linear')

In [20]:
clf.get_params(deep=True)

{'C': 1,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [21]:
print('yi * alpha_i: \n', clf.dual_coef_)
print('Number of support vectors of each class:', clf.n_support_)

yi * alpha_i: 
 [[-0.499944   0.3999552  0.0999888]]
Number of support vectors of each class: [1 2]


In [22]:
alphas = np.abs(clf.dual_coef_)

In [23]:
labels = np.sign(clf.dual_coef_)

In [24]:
for i in range(len(alphas)):
    print('label = ',labels[i],"\t",'alpha= ',alphas[i])

label =  [-1.  1.  1.] 	 alpha=  [0.499944  0.3999552 0.0999888]


In [25]:
sum_values = 0  
for i in range(len(alphas)):
    sum_values += labels[0][i] * alphas[0][i]
sum_values

-0.49994400000000006

In [26]:
labels[0][0]

-1.0

In [27]:
alphas[0][0]

0.49994400000000006

In [28]:
np.insert(clf.dual_coef_, 1, 0).reshape(-1,1)

array([[-0.499944 ],
       [ 0.       ],
       [ 0.3999552],
       [ 0.0999888]])

In [29]:
alphas

array([[0.499944 , 0.3999552, 0.0999888]])

In [31]:
print(np.sum(((X)*(np.insert(clf.dual_coef_, 1, 0).reshape(-1,1))),axis=0))

[ 0.5999328 -0.7999104]
